// <auto-generated />
using DtAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DtAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210916113327_InitialDatabaseMigration")]
    partial class InitialDatabaseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DtAPI.DtApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("durum")
                        .HasColumnType("int");

                    b.Property<string>("ilan_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilan_data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kurum_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unique_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DtApis");
                });
#pragma warning restore 612, 618
        }
    }
}
